### ISSUE TITLE
Division of roles

### ISSUE THREAD

**Issue by isaomatsunami** [d3/d3-shape#108]
This is just a question.
Value() method does not play a role of "value" but just an accessor. Transform to numerical value is done by "+" inside main function. Isn't it a little confusing?
I know good boys must preprocess data before feeding stack().

**Comment by mbostock** [comment]
The value accessor returns the value for the corresponding datum and key, so I think it’s named accurately. The `+` is there just to coerce the value to a number in case the value accessor doesn’t return a number; a well-behaved value accessor should return a number, so in the normal case the `+` does nothing.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
