### ISSUE TITLE
pie() / arc() rendering bug for specific combination of radii

### ISSUE THREAD

**Issue by danburzo** [d3/d3-shape#119]
While toying with the parameters for `pie` and `arc`, [I have found a glitch](https://beta.observablehq.com/@danburzo/d3-shape-bug) for this configuration:

```js
{
  "innerRadius": 23,
  "outerRadius": 128,
  "cornerRadius": 14,
  "padAngle": 0.06,
  "values": [6, 6]
}
```

Which outputs this shape:

<img width="285" alt="screen shot 2018-03-07 at 17 59 40" src="https://user-images.githubusercontent.com/205375/37102811-5938b59e-2231-11e8-8566-bc6d8c527579.png">

Not sure if it warrants further investigation, but I wanted to let you know. 

Seems to be a kind of floating point error, since it happens only on specific combinations of values and radii.

Other combinations can cause different glitches:

```js
{
  "innerRadius": 20,
  "outerRadius": 115,
  "cornerRadius": 13,
  "padAngle": 0.06,
  "values": [ 6, 6 ]
}
```

Outputs the shape below:

<img width="252" alt="screen shot 2018-03-07 at 18 30 19" src="https://user-images.githubusercontent.com/205375/37104532-a0e73b28-2235-11e8-9596-86fa2f2b768f.png">

**Comment by mbostock** [comment]
Confirmed. https://beta.observablehq.com/@mbostock/d3-arc-rounded-corner-issue

Most likely related to this test:

https://github.com/d3/d3-shape/blob/master/src/arc.js#L152

**Comment by mbostock** [comment]
Just noticed you already linked to an Observable notebook to reproduce this issue. Well played, sir.

**Comment by danburzo** [comment]
I wouldn't _dare_ show up without an Observable notebook to reproduce this issue! :)

Would you say that it's benign that the `pie()` generator produces π as the angle for most value pairs, but "almost π" for `[6, 6]`? (I still have to read more carefully through the code to have any useful points to make).

**Comment by mbostock** [comment]
It’s not exactly π because the padAngle is non-zero.

**Comment by danburzo** [comment]
Looking through the code for the `pie()` generator, it seems that in the case of N identical values, the padAngle gets eliminated and the angle for each slice is (2 * π / N), which for N = 2 gives us π — in most cases, except that for `[6, 6]` it's almost-pie. 

(Not sure if it's relevant but it seems counter-intuitive for the padAngle to evaporate in these specific cases?)
