### ISSUE TITLE
curvePoints?

### ISSUE THREAD

**Issue by Fil** [d3/d3-shape#154]
When drawing a line with dots, it would be easier to use a curve to draw the individual points, rather than a specific loop. https://observablehq.com/d/5c4650cfb7214d6c

![image](https://user-images.githubusercontent.com/7001/70264611-14864380-1799-11ea-9ad4-06b2c648bd81.png)

The image is obtained by first drawing:
>  line.curve(d3.curveLinear)(data) + stroke

then:
> line.curve(curvePoints(4))(data) + orange fill + stroke

(The code is rather simple)

**Comment by mbostock** [comment]
Sounds good.

**Comment by Fil** [comment]
I'll work on a PR. 

I've checked that it works well with defined(). I also looked for a more generic API which would allow `curvePoint().pointRadius((d,i,e) => scaleRadius(d))`, but at this level you only receive the accessed (x,y), and not the original (d,i,e) data point.

**Comment by Fil** [comment]
A useful alternative could be curveSymbol, which would allow to pass in any d3.symbol type; it works in canvas but, since we don't have context.translate() for the SVG version of d3.path, I'm not sure how to do it
https://observablehq.com/d/5dda94b18c93e92b

**Comment by Fil** [comment]
need to reconsider, if there is interest, because so much is possible differently
