### ISSUE TITLE
need help achieving this shape

### ISSUE THREAD

**Issue by zilahir** [d3/d3-shape#167]
Hey! 

It's a shame, but I cant figure this out myself, so came here for help. 

I want to achieve a shape like this: 

![image](https://user-images.githubusercontent.com/6687149/90988016-25315080-e598-11ea-904e-8f742b501b7b.png)

I have something similar already done, using `.curve()` but it's not quite still: 

```
const width = 1600
const height = 64
cons tabWidth = 160
const tab = shape.line().x(d => d.x).y(d => d.y).curve(shape.curveBasis)([
			{ x: width, y: 0 },
			{ x: width + 5, y: 0 },
			{ x: width + 10, y: 10 },
			{ x: width + 15, y: height },
			{ x: width + tabWidth - 15, y: height },
			{ x: width + tabWidth - 10, y: 10 },
			{ x: width + tabWidth - 5, y: 0 },
			{ x: width + tabWidth, y: 0 },
		]);
```

![image](https://user-images.githubusercontent.com/6687149/90988046-54e05880-e598-11ea-8eef-d0b085859d77.png)

Can you help me achieve the desired shape? 

Thank you!

**Comment by curran** [comment]
You can use the rx attribute on a rect element.

This is not the right forum for asking for help - please try asking in the #help channel of https://d3-slackin.herokuapp.com/
