### ISSUE TITLE
arc({cornerRadius})

### ISSUE THREAD

**Issue by Fil** [d3/d3-shape#169]
`arc.cornerRadius(10)` works as expected, but `arc({cornerRadius: 10})` doesn't.
https://observablehq.com/d/ee9bef73d446e156
![test](https://user-images.githubusercontent.com/7001/96740423-1fea5980-13c1-11eb-9f32-f9188e663d2e.png)

should it?

**Comment by mbostock** [comment]
Expected https://github.com/d3/d3-shape#arc_cornerRadius

**Comment by Fil** [comment]
surprising nonetheless :)
