### ISSUE TITLE
The pie arguments problem

### ISSUE THREAD

**Issue by Benbinbin** [d3/d3-shape#186]
according to [document](https://github.com/d3/d3-shape#:~:text=Any%20additional%20arguments%20are%20arbitrary%3B%20they%20are%20simply%20propagated%20to%20the%20pie%20generator%E2%80%99s%20accessor%20functions%20along%20with%20the%20this%20object.)

> Any additional _arguments_ are arbitrary; they are simply propagated to the pie generator’s accessor functions along with the `this` object.

and it should be [call the pie generator](https://github.com/d3/d3-shape#_pie) like this `pie(data[, arguments…])`

refer to the way to [call the arc generator](https://github.com/d3/d3-shape#_arc) 

```js
const arc = d3.arc();

arc({
  innerRadius: 0,
  outerRadius: 100,
  startAngle: 0,
  endAngle: Math.PI / 2
}); // "M0,-100A100,100,0,0,1,100,0L0,0Z"
```

I try the similar way to call the pie generator but it doesn't work

```js
pie(data, {
  padAngle: padAngle
});
```

it seems like the way to treat the arguments in [arc generator](https://github.com/d3/d3-shape/blob/main/src/arc.js#L5-L23) and [pie generator](https://github.com/d3/d3-shape/blob/main/src/pie.js#L11-L13) is different.

which is the correct way to pass the arguments in pie generator?

**Comment by Fil** [comment]
It just means that if *f* is a function and you call pie.startAngle(*f*)(data, "hello", "it's me"), f will be called with the arguments (data, "hello", "it's me").

In this case, if you have
```
    pie = d3.pie()
      .padAngle((_, { padAngle, padAngleDegrees = 0 } = {}) =>
        padAngle === undefined ? (padAngleDegrees * Math.PI) / 180 : padAngle
      )

```
you might call
```
     pie(data, {padAngleDegrees: 1}) 
```
and it will compute the padAngle in radians from the value given in degrees.
