### ISSUE TITLE
How does Catmull Rom work with a Bézier curve?

### ISSUE THREAD

**Issue by pspeter3** [d3/d3-shape#196]
This isn’t an issue as much as a question. Every article I’ve read about Catmull Rom interpolates all the points in between but this implementation uses the Bézier curve function on Path2D / Canvas. How does that work? Thank you in advance for your time / explanation.

**Comment by Fil** [comment]
It's a good question :)

https://github.com/d3/d3-shape/blob/289b6ca78ba2fdde523737651866405ec6035587/src/curve/catmullRom.js#L10 implements equation (2) of the paper indicated in #18.

**Comment by pspeter3** [comment]
Thank you so much! I'll check out the paper.
