### ISSUE TITLE
running tests with d3-shape

### ISSUE THREAD

**Issue by Ludo05** [d3/d3-shape#203]
Hi thanks for your great library,

I am having issues running tests with jest, typescript and d3-shapes.

When running the tests I am running into this issue

![Screenshot 2022-09-30 at 20 01 36](https://user-images.githubusercontent.com/35262933/193339661-461acd91-cbbe-4428-a7c9-dc5f7e33d110.png)

my jest.config looks like 
 transformIgnorePatterns: [
    'node_modules/d3-shape',
  ],

but still no success. 
Any help would be really appreciated.

**Comment by Fil** [comment]
see https://github.com/d3/d3-array/issues/255
