### ISSUE TITLE
d3-shape package is missing deep export declations

### ISSUE THREAD

**Issue by gka** [d3/d3-shape#213]
In order to deep-import parts of d3-shape in a vite project, e.g. using

```js
import arc from 'd3-shape/src/arc.js';
```

the package.json needs to list the paths individually. So instead of 

```json
  "exports": {
    "umd": "./dist/d3-shape.min.js",
    "default": "./src/index.js"
  },
```
the sections needs to look like this
```json
  "exports": {
    ".": {
      "umd": "./dist/d3-shape.min.js",
      "require": "./dist/d3-shape.min.js",
      "import": "./src/index.js"
    },
    "./src/*.js": {
      "import": "./src/*.js"
    },
    "./src/curve/*.js": {
      "import": "./src/curve/*.js"
    },
    "./src/offset/*.js": {
      "import": "./src/offset/*.js"
    },
    "./src/order/*.js": {
      "import": "./src/order/*.js"
    },
    "./src/symbol/*.js": {
      "import": "./src/symbol/*.js"
    }
  },
```
Unfortunately the `exports` declaration does not support the `/**/` wildcard, so each folder needs to be listed separately.

**Comment by mbostock** [comment]
This is an intentional omission. The structure of the sources isn’t part of the public API; this library is instead exposed as a single entry point.

**Comment by gka** [comment]
Hi @mbostock, thanks for getting back. I can see why you'd not want to expose the internal structure as part the public API.

And in theory, a good bundler should be able to tree-shake the code so only the imported modules are included (it works in [bundlejs.com](https://bundlejs.com/?q=d3-shape%403.2.0&treeshake=%5B%7B+arc+%7D%5D&config=%7B%22analysis%22%3A%22treemap%22%7D), for instance). Unfortunately, this is [currently not the case](https://github.com/vitejs/vite/issues/16720) in **Vite** projects, and until this gets fixed, it means Vite users have to rely on deep-imports to keep the bundle size down. 

In case of the d3js ecosystem, it means that currently, the only option I have to avoid including _all_ scales/shapes/geo projections/etc is to _copy individual code files_ from d3 modules into my project, which is a major inconvenience, to say the least.

**Comment by mbostock** [comment]
I’m sorry that Vite isn’t able to tree-shake the code efficiently, but that sounds like a problem that should be fixed in Vite rather than every module. Asking every package to opt-out of Node’s export declarations to workaround the limitations of a single (albeit popular) bundler doesn’t seem practical.

**Comment by sapphi-red** [comment]
@gka Hi, Vite maintainer here :wave:
I checked [the output of `import { arc } from 'd3-shape'; console.log(arc)`](https://stackblitz.com/edit/vitejs-vite-hw6ywd?file=dist%2Fassets%2Findex-C_vZdFuE.js&terminal=build) and it only contained the needed code.
I also roughly checked the code in this repo, and it was written in a tree-shaking friendly way.
Would you point out the part you think it can be trimmed down and make an issue on Vite repo?
