### ISSUE TITLE
Link (diagonal)?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-shape#27]
It’s quite likely we actually want to call this a _link_ (shape) and put it in the [d3-hierarchy module](https://github.com/d3/d3-hierarchy), since this shape is typically used to represent links in hierarchical visualizations.

**Comment by mbostock** [comment]
I dunno… Seems pretty generic and this seems like a reasonable place for it.

```js
function diagonal(d) {
  return "M" + d.source.y + "," + d.source.x
      + "C" + (d.source.y + d.target.y) / 2 + "," + d.source.x
      + " " + (d.source.y + d.target.y) / 2 + "," + d.target.x
      + " " + d.target.y + "," + d.target.x;
}
```

**Comment by mbostock** [comment]
Also if you want it to render to both Canvas and SVG, then it becomes even more tedious to not have this available in d3-shape.

**Comment by ZephryL** [comment]
Hi there Mike. I use the svg.diagonal to associate arbitrary shapes (i.e. not necessarily links in a formal hierarchy) like this:
'var diagonal = d3.svg.diagonal().projection(function (d) { return [d.y, d.x]; });'
I'm at a loss as to how I would implement this behavior in version 4. How would you suggest I go about this?
Thanks!

**Comment by ZephryL** [comment]
Sorry Mike, I was being a dork. Sorted with your simple `link(d)` function, which I initially ignored. Apologies

**Comment by brettbibby** [comment]
I'm not understanding this exchange very well between you guys.

Old:
var diagonal = d3.svg.diagonal().projection(function (d) { return [d.y, d.x]; });

New???

Sorry to disturb!

**Comment by mbostock** [comment]
Here are some examples…

* [Dendrogram](http://bl.ocks.org/mbostock/ff91c1558bc570b08539547ccc90050b)
* [Radial Dendrogram](http://bl.ocks.org/mbostock/4739610f6d96aaad2fb1e78a72b385ab)
* [Tidy Tree](http://bl.ocks.org/mbostock/9d0899acb5d3b8d839d9d613a9e1fe04)
* [Radial Tidy Tree](http://bl.ocks.org/mbostock/2e12b0bd732e7fe4000e2d11ecab0268)
* [Tidy Tree vs. Dendrogram](http://bl.ocks.org/mbostock/e9ba78a2c1070980d1b530800ce7fa2b)

**Comment by brettbibby** [comment]
Perfect, thanks!

**Comment by ZephryL** [comment]
Thanks you Mike. Appreciate your time.

**Comment by joshburgess** [comment]
Is there an example anywhere of how we could recreate the standard straight line behavior found in the "Classic OrgChart" in the following example using D3 V3? 

http://blog.zubasoft.at/Examples/D3.js/OrgChart/index.htm

It uses this function:

```
d3.svg.line()
    .x(function(d) { return d.x; })
     .y(function(d) { return d.y; })
      .interpolate("linear");

```

like this:

```
// Enter any new links at the parent's previous position.
link.enter().append("path" , "g")
  .attr("class", "link")
  .attr("d", function(d) {
    var u_line = (function (d) {
    var u_linedata = [
      {"x": d.source.x0 + parseInt(_rectW / 2), "y": d.source.y0 + _rectH + 2 },
      {"x": d.source.x0 + parseInt(_rectW / 2), "y": d.source.y0 + _rectH + 2 },
      {"x": d.source.x0 + parseInt(_rectW / 2), "y": d.source.y0 + _rectH + 2 },
      {"x": d.source.x0 + parseInt(_rectW / 2), "y": d.source.y0 + _rectH + 2 }
    ];
    return u_linedata;
})(d);
return _lineFunction(u_line);
});
```

I'm having some trouble trying to figure out how to programmatically recreate these paths with the D3 V4 API... I think these types of things are where including built-in D3 functions for creating links could help out a lot.

**Comment by mbostock** [comment]
It’s trivial to adjust that line function definition for V4:

```js
var line = d3.line()
    .x(function(d) { return d.x; })
    .y(function(d) { return d.y; })
    .curve(d3.curveLinear);
```

The rest of what you described is unchanged.

**Comment by joshburgess** [comment]
Ah, okay. I thought I needed to provide the SVG path syntax with M, C, H, L, etc.... My data set is a bit different than what's given, so I wasn't using the exact u_linedata array there... just using it as an example.

**Comment by mbostock** [comment]
The simplest option here is to have two variants of a *link* shape: one with vertical tangents and one with horizontal tangents:

```js
function linkHorizontal(d) {
  return "M" + d.source.x + "," + d.source.y
      + "C" + d.source.x +  "," + (d.source.y + d.target.y) / 2
      + " " + d.target.x + "," + (d.source.y + d.target.y) / 2
      + " " + d.target.x + "," + d.target.y;
}

function linkVertical(d) {
  return "M" + d.source.x + "," + d.source.y
      + "C" + (d.source.x + d.target.x) / 2 + "," + d.source.y
      + " " + (d.source.x + d.target.x) / 2 + "," + d.target.y
      + " " + d.target.x + "," + d.target.y;
}
```

Then, in conjunction with d3/d3-hierarchy#63, it becomes much easier to change the orientation of a hierarchical layout and its links without the complexity of *diagonal*.projection from 3.x.

There’s a related question whether we want the midpoint of the link to be configurable: should it be specified as a parameter *t* in [0, 1], or as a fixed offset from the source or target? Of course, it’s probably sufficient to just keep it simple and not configurable. But if we want to be forwards-compatible then linkVertical should return a link generator function (like d3.line) rather than being a static, non-configurable shape generator.

**Comment by mbostock** [comment]
We will also need a radial link.

**Comment by jeshicawang** [comment]
Hi, I'm having trouble with the transition for the link when collapsing and expanding the tree diagram. The path line starts doing weird things. What would be the correct way to transition the path?

`
link.enter().append('path')
    .attr('class', 'link')
    .attr('d', d => {
      return "M" + d.parent.x + "," + d.parent.y
        + "C" + d.parent.x + "," + (d.y + d.parent.y) / 2
        + " " + d.parent.x + "," + (d.y + d.parent.y) / 2
        + " " + d.parent.x + "," + d.parent.y;
    })
  .transition(t)
    .attr('d', d => {
      return "M" + d.x + "," + d.y
        + "C" + d.x + "," + (d.y + d.parent.y) / 2
        + " " + d.parent.x + "," + (d.y + d.parent.y) / 2
        + " " + d.parent.x + "," + d.parent.y;
    });
`

**Comment by gauravtyagi77** [comment]
Hi @mbostock,

In my code written by someone else earlier for rendering d3-sankey with d3 v3 js by using diagonal is given below.

var path = d3.svg.diagonal()
    .source(function(d) {
        return {"x":d.source.y + d.source.dy / 2,
                "y":d.source.x + sankey.nodeWidth()/2};
    })            
    .target(function(d) {
        return {"x":d.target.y + d.target.dy / 2,
                "y":d.target.x + sankey.nodeWidth()/2};
    })
    .projection(function(d) { return [d.y, d.x]; });

Can you help me how should I replace my calculation with your.

**Comment by Malex** [comment]
I read all the exchange, and while I am an happy user of linkVertical/Horizontal and such, I'm having trouble implementing a different kinda of connection, as per example http://bl.ocks.org/jdarling/2503502
Is there an API I'm missing to get something similar?

**Comment by specialCoder** [comment]
> I dunno… Seems pretty generic and this seems like a reasonable place for it.
> 
> ```js
> function link(d) {
>   return "M" + d.source.y + "," + d.source.x
>       + "C" + (d.source.y + d.target.y) / 2 + "," + d.source.x
>       + " " + (d.source.y + d.target.y) / 2 + "," + d.target.x
>       + " " + d.target.y + "," + d.target.x;
Horizontal:
function link(d) {
    return `M${d.source.y},${d.source.x}C${(d.source.y + d.target.y) / 2},${d.source.x} ${(d.source.y + d.target.y) / 2},${d.target.x} ${d.target.y},${d.target.x}`;
  }
Verticle:
function link(d) {
    return `M${d.source.x},${d.source.y}C${(d.source.x + d.target.x) / 2},${d.target.y} ${(d.source.x + d.target.x) / 2},${d.source.y} ${d.target.x},${d.target.y}`;
  }
