### ISSUE TITLE
Use high DPI canvas in examples at bl.ocks.org

### ISSUE THREAD

**Issue by devgru** [d3/d3-shape#53]
d3-shape examples at bl.ocks.org are blurry

It can be easily fixed by using `getRetinaRatio()` from this block: http://bl.ocks.org/devgru/a9428ebd6e11353785f2

**Comment by mbostock** [comment]
Not sure whether I want to add this boilerplate to all the examples; it’s more cruft for new learners to wade through before understanding the d3-shape API. Arguably this is a reason to write the examples using SVG, which would automatically upscale for retina, though that would require using d3-selection… Anyway. Thank you for the suggestion. I’ll consider it, but I don’t feel the need to track this as an issue.
