### ISSUE TITLE
Specify loop range

### ISSUE THREAD

**Issue by sherdeadlock** [d3/d3-shape#63]
Shape loop all the data. Can it provide an API that specifying a range? ex:
```js
area(data, 5000, 6000);
```

**Comment by mbostock** [comment]
Use [*array*.slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)?

```js
area(data.slice(5000, 6000));
```

**Comment by sherdeadlock** [comment]
It can improve some performance while changing range rapidly.

**Comment by mbostock** [comment]
I’m skeptical that *array*.slice is the performance bottleneck here. But, you could avoid the allocation in *array*.slice by copying into a pre-existing array. Or you can use [*area*.defined](https://github.com/d3/d3-shape#area_defined) to consider a subset of the array:

```js
area.defined(function(d, i) { return 5000 >= i && i < 6000; })(data);
```
