### ISSUE TITLE
bundle curve throws error with area

### ISSUE THREAD

**Issue by jharris4** [d3/d3-shape#70]
While trying out the various curves with an area shape generator I noticed that I get the following error when using the bundle curve:

`Uncaught TypeError: output.areaStart is not a function`

which occurs at this line of [area.js](https://github.com/d3/d3-shape/blob/ca59f9c0d767184f53b73326cd76035de54f9c4c/src/area.js#L34)

It works fine with the line generator, and I see that bundle-test.js doesn't have any tests for areas.

I guess this means bundle curves are only designed to work with lines?

In case you want a quick way to reproduce, I've attached a short example
[index_html.txt](https://github.com/d3/d3-shape/files/303741/index_html.txt)

**Comment by mbostock** [comment]
Correct, d3.curveBundle is only intended to work with d3.line. It’s for hierarchical edge bundling, not for rendering areas. I’ll update the documentation accordingly.

**Comment by jharris4** [comment]
awesome, thanks for clearing that up!

**Comment by fabswt** [comment]
Was there any particular reason for reserving `d3.curveBundle` to the interpolation of lines to the exclusion of areas, starting in v4? 

Back in D3 v3, I could use it on areas as well (e.g.: `.interpolate("bundle").tension(0)`).

FYI, I needed it in v4/v5 as well, so created a custom curve for it [with some help from StackOverflow](https://stackoverflow.com/questions/50542573/d3-custom-curve-bundle-interpolation-for-areas/50574541#50574541).
