### ISSUE TITLE
https://d3js.org/d3-path.v0.2.min.js not available any longer

### ISSUE THREAD

**Issue by DavidBruant** [d3/d3-shape#72]
It's mentioned in the [install steps](https://github.com/d3/d3-shape#installing)

**Comment by DavidBruant** [comment]
Changing to `v1` seems to do the job fine

**Comment by mbostock** [comment]
Sorry, I accidentally published them as https://d3js.org/d3-path.v0.3.js and https://d3js.org/d3-path.v0.3.min.js. (They were still published correctly to https://npmcdn.com/d3-path@0.2/, but my publishing process to d3js.org is partly manual and thus capable of error.) I’ve renamed the files to fix the issue. In the very near future d3-shape will be released as 1.0.0 and I’ll upgrade the d3-path dependency to 1.0.0 at the same time. Thanks for the report and sorry for the inconvenience!

**Comment by DavidBruant** [comment]
No worries, thanks for the quick reaction :-)
