### ISSUE TITLE
Expose ascending -> sum

### ISSUE THREAD

**Issue by ericsoco** [d3/d3-shape#86]
When writing a custom stack order, it can be useful to have access to the [`sum()` function](https://github.com/d3/d3-shape/blob/master/src/order/ascending.js#L8-L12) exported from [`ascending.js`](https://github.com/d3/d3-shape/blob/master/src/order/ascending.js).

Any reason not to expose it in [`d3-shape::index.js`](https://github.com/d3/d3-shape/blob/master/index.js)?

**Comment by mbostock** [comment]
I ask the opposite question, which is: is the utility of the *sum* function worth the cost to expose it? Every addition to the public API has a cost: writing the documentation, asking readers to read (or skip) said documentation, and committing to a stable API (that requires a major version bump to change). 

By default, I prefer to keep as much as I can private. The *sum* function doesn’t seem useful enough to me to merit a new public API, especially when there’s already [d3.sum](https://github.com/d3/d3-array/blob/master/README.md#sum) which can be used as `d3.sum(series, d => d[1])`.

**Comment by mbostock** [comment]
Also, if you don’t want to use d3.sum, you can just copy the implementation of *sum* into your custom stack order. It’s pretty small, so a little duplication doesn’t seem harmful.

**Comment by ericsoco** [comment]
Didn't think about using d3.sum here, that fits the bill nicely. I was mostly trying to modify stackOrderInsideOut, and so needed ascending.sum -- indeed, I just copied it into my code.

Your reasons make plenty of sense, thanks for taking the time to explain them! Cheers.
