### ISSUE TITLE
example of stacked polar bar chart

### ISSUE THREAD

**Issue by noahehall** [d3/d3-shape#88]
in the readme there is a line saying 'Specifying the inner radius as a function is useful for constructing a stacked polar bar chart, often in conjunction with a sqrt scale. '

Are there any examples of this? thx

**Comment by mbostock** [comment]
Usually it’s a bad idea. But here you go: https://bl.ocks.org/mbostock/6fead6d1378d6df5ae77bb6a719afcb2

**Comment by noahehall** [comment]
Thanks @mbstock
