### ISSUE TITLE
Request an Updated d3.stack() Example

### ISSUE THREAD

**Issue by drewpc** [d3/d3-shape#93]
The changes from v3 (`d3.layout.stack`) to v4 (`d3.stack`) are confusing because it seems that the the new function cannot operate on the same data.  For example, I attempted to convert the [stacked to multiples example](https://bl.ocks.org/mbostock/4679202) from v3 to v4.  Based on [the CHANGELOG comment about the `stack.out` function](https://github.com/d3/d3/blame/master/CHANGES.md#L1042), I can't figure out how to use the exact same data from the v3 version and still use the new function.  Can someone add a new example or further clarify how to use the new stack function with the same data from the v3 implementation?

**Comment by mbostock** [comment]
* https://bl.ocks.org/mbostock/3886208
* https://bl.ocks.org/mbostock/b5935342c6d21928111928401e2c8608

**Comment by mbostock** [comment]
* https://bl.ocks.org/mbostock/4060954

**Comment by indepth2** [comment]
Anyone ever get the stacked-to-multiples example working in D3 V4?  I've been working on it for hours and just can't get it.  I can only imagine how busy Mike must be; but based on my experience and A LOT of the questions/comments on stack exchange, I think it would really helpful to a lot of us to see some of these EXACT V3 examples we've been using updated to work with V4.

**Comment by drewpc** [comment]
Nope.  The examples given prior to closing this request don't address the issue.  I ended up having to go back to D3 v3 in order to do what I needed to.

**Comment by indepth2** [comment]
Thanks Drew.  I'm going to give it one more try, but man there are just so many differences in the way things are done.  And I'm not exactly proficient in D3 at this point.

**Comment by indepth2** [comment]
Hey Drew, I had posted this over on stack exchange as well and (it took about a week) but someone did finally go ahead and convert the example to V4 for me.  Here is the link to the jsFiddle they provided: https://jsfiddle.net/levvsha/vrbq7ebz/
